import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flexGrow: 1,
    paddingHorizontal: 20,
    paddingTop: 10,
  },
  headerIconBtn: {
    padding: 6,
  },
  circleIconBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  flexGridWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    width: '100%',
  },
  pillSearchBox: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 22,
    borderWidth: 1,
    paddingHorizontal: 16,
    paddingVertical: 10,
    marginBottom: 14,
  },
  pillSearchInput: {
    flex: 1,
    fontSize: 14,
  },
  genreBannerCard: {
    height: 140,
    borderRadius: 18,
    marginBottom: 14,
    overflow: 'hidden',
  },
  genreBannerBg: {
    width: '100%',
    height: '100%',
    justifyContent: 'flex-end',
    padding: 14,
  },
  bannerDarkOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(11, 13, 18, 0.45)',
  },
  bannerTagRow: {
    backgroundColor: 'rgba(233, 69, 96, 0.25)',
    alignSelf: 'flex-start',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 10,
    marginBottom: 4,
    zIndex: 2,
  },
  bannerTagText: {
    fontSize: 9,
    fontWeight: '800',
    letterSpacing: 1,
  },
  bannerTitleText: {
    fontSize: 22,
    fontWeight: '900',
    zIndex: 2,
  },
  bannerSubText: {
    fontSize: 12,
    color: 'rgba(255, 255, 255, 0.8)',
    marginTop: 2,
    zIndex: 2,
  },
  resultsHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  resultsTitleText: {
    fontSize: 18,
    fontWeight: '800',
  },
  resultsCountText: {
    fontSize: 12,
    fontWeight: '600',
  },
  centerLoader: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  gridContentList: {
    paddingBottom: 28,
  },
  gridColumnWrapper: {
    justifyContent: 'space-between',
  },
  emptySubmitCard: {
    borderRadius: 20,
    borderWidth: 1,
    padding: 24,
    alignItems: 'center',
    marginVertical: 20,
  },
  emptyIconCircle: {
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: 'rgba(233,69,96,0.12)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  emptySubmitTitle: {
    fontSize: 18,
    fontWeight: '800',
    marginBottom: 6,
    textAlign: 'center',
  },
  emptySubmitSub: {
    fontSize: 13,
    textAlign: 'center',
    lineHeight: 18,
    marginBottom: 16,
  },
  submitGenreBtn: {
    borderRadius: 22,
    paddingHorizontal: 20,
    paddingVertical: 12,
  },
  submitGenreBtnText: {
    fontSize: 14,
    fontWeight: '700',
  },
  bottomSuggestCard: {
    borderRadius: 20,
    borderWidth: 1,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 14,
    marginBottom: 20,
  },
  suggestIconBadge: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(233,69,96,0.12)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  suggestCardTitle: {
    fontSize: 14,
    fontWeight: '700',
  },
  suggestCardSub: {
    fontSize: 12,
    marginTop: 2,
  },
  sheetOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.7)',
    justifyContent: 'flex-end',
  },
  sheetContainer: {
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    borderWidth: 1,
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 28,
  },
  sheetHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  sheetTitleText: {
    fontSize: 18,
    fontWeight: '900',
    letterSpacing: 1,
  },
  filterSection: {
    marginBottom: 18,
  },
  sheetSectionLabel: {
    fontSize: 11,
    fontWeight: '800',
    color: 'rgba(255,255,255,0.6)',
    letterSpacing: 1,
    marginBottom: 8,
  },
  dropdownBtn: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.15)',
    backgroundColor: 'rgba(255,255,255,0.06)',
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  dropdownBtnText: {
    fontSize: 14,
    fontWeight: '600',
  },
  dropdownMenuBox: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.15)',
    marginTop: 6,
    maxHeight: 180,
  },
  dropdownMenuItem: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.06)',
  },
  dropdownMenuItemActive: {
    backgroundColor: 'rgba(233,69,96,0.2)',
  },
  dropdownMenuItemText: {
    fontSize: 13,
  },
  chipOptionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  filterChipOption: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    backgroundColor: 'rgba(255,255,255,0.06)',
    paddingHorizontal: 14,
    paddingVertical: 8,
    marginRight: 8,
    marginBottom: 8,
  },
  filterChipOptionSelected: {
    backgroundColor: 'rgba(233,69,96,0.25)',
  },
  filterChipOptionText: {
    fontSize: 12,
    color: 'rgba(255,255,255,0.7)',
  },
  filterChipOptionTextSelected: {
    fontWeight: '700',
  },
  sheetFooterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 14,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.1)',
  },
  clearAllBtn: {
    paddingVertical: 10,
    paddingHorizontal: 14,
  },
  clearAllBtnText: {
    fontSize: 14,
    fontWeight: '600',
    color: 'rgba(255,255,255,0.6)',
  },
  applyBtn: {
    borderRadius: 22,
    paddingVertical: 11,
    paddingHorizontal: 22,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 10,
    elevation: 6,
  },
  applyBtnText: {
    fontSize: 14,
    fontWeight: '700',
  },
});
